version: '3.8'

services:
  oracledb:
    build: .
    image: oracledb_custom
    container_name: oracledb_container
    environment:
      - ORACLE_PASSWORD=adminpassword
      - ORACLE_DATABASE=uptc
      - APP_USER=hr
      - APP_USER_PASSWORD=uptc
    ports:
      - "1521:1521"
    volumes:
      - oracledb_data:/opt/oracle/oradata
      - ./init_scripts:/container-entrypoint-initdb.d

volumes:
  oracledb_data:
