version: '3.8'

services:
  mariadb:
    build: .
    image: mariadb_custom
    container_name: mariadb_container
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: gestion_emp
      MARIADB_USER: usuario
      MARIADB_PASSWORD: contrasena
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init_scripts:/docker-entrypoint-initdb.d

volumes:
  mariadb_data:
